a,b=map(int,input("Nhap hai so a,b: ").split())
cal=input("Nhap phep tinh (+,-,*,/,//,%,**): ")
if(cal=='+'): print(a+b)
elif(cal=='-'): print(a-b)
elif(cal=='*'): print(a*b)
elif(cal=='/'): print(a/b)
elif(cal=='//'): print(a//b)
elif(cal=='**'): print(a**b)
else: print(a%b)